version: "3.9"

services:
  web:
    build: server
    networks:
      wan:
        ipv4_address: 172.25.0.10
      lan:
        ipv4_address: 172.24.14.10
  walusiak:
    build: host
    networks:
      lan:
        ipv4_address: 172.24.14.20

networks:
  wan:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.25.0.0/24
          gateway: 172.25.0.1
  lan:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.24.14.0/24
          gateway: 172.24.14.1

